language: php

php:
  - 5.3
  - 5.4
  - hhvm

before_script:
  - sudo apt-get update
  - sudo apt-get install hhvm -qq -y --force-yes
  - composer self-update
  - composer install --prefer-source

script: phpunit -c tests/phpunit.xml.dist

notifications:
  irc: "irc.freenode.org#jackalope"
