language: php

php:
  - 5.3
  - 5.4
  - hhvm

before_script:
  - if [ $(phpenv version-name) = "hhvm" ]; then sudo apt-get update; fi
  - if [ $(phpenv version-name) = "hhvm" ]; then sudo apt-get install hhvm -qq -y --force-yes; fi
  - composer self-update
  - composer install --prefer-source

script: phpunit -c tests/phpunit.xml.dist

notifications:
  irc: "irc.freenode.org#jackalope"
